// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: FullTest

#include "../ui.h"

void ui_Display_screen_init(void)
{
ui_Display = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Display, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_back_to_index1 = lv_btn_create(ui_Display);
lv_obj_set_width( ui_back_to_index1, 100);
lv_obj_set_height( ui_back_to_index1, 50);
lv_obj_add_flag( ui_back_to_index1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_back_to_index1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_back_to_index1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label11 = lv_label_create(ui_back_to_index1);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"BACK");
lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Spinner1 = lv_spinner_create(ui_Display,1000,90);
lv_obj_set_width( ui_Spinner1, 100);
lv_obj_set_height( ui_Spinner1, 100);
lv_obj_set_x( ui_Spinner1, -132 );
lv_obj_set_y( ui_Spinner1, -17 );
lv_obj_set_align( ui_Spinner1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Spinner2 = lv_spinner_create(ui_Display,1000,90);
lv_obj_set_width( ui_Spinner2, 80);
lv_obj_set_height( ui_Spinner2, 80);
lv_obj_set_x( ui_Spinner2, -96 );
lv_obj_set_y( ui_Spinner2, -66 );
lv_obj_set_align( ui_Spinner2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner2, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Spinner3 = lv_spinner_create(ui_Display,1000,90);
lv_obj_set_width( ui_Spinner3, 130);
lv_obj_set_height( ui_Spinner3, 130);
lv_obj_set_x( ui_Spinner3, -161 );
lv_obj_set_y( ui_Spinner3, 64 );
lv_obj_set_align( ui_Spinner3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner3, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_arc_color(ui_Spinner3, lv_color_hex(0x0000FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner3, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Colorwheel2 = lv_colorwheel_create(ui_Display,true);
lv_obj_set_width( ui_Colorwheel2, 200);
lv_obj_set_height( ui_Colorwheel2, 200);
lv_obj_set_x( ui_Colorwheel2, 54 );
lv_obj_set_y( ui_Colorwheel2, -30 );
lv_obj_set_align( ui_Colorwheel2, LV_ALIGN_CENTER );
lv_obj_set_style_arc_width(ui_Colorwheel2, 30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Spinner4 = lv_spinner_create(ui_Display,1000,90);
lv_obj_set_width( ui_Spinner4, 80);
lv_obj_set_height( ui_Spinner4, 80);
lv_obj_set_x( ui_Spinner4, -99 );
lv_obj_set_y( ui_Spinner4, 106 );
lv_obj_set_align( ui_Spinner4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner4, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_color(ui_Spinner4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Spinner4, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner4, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Spinner5 = lv_spinner_create(ui_Display,1000,90);
lv_obj_set_width( ui_Spinner5, 100);
lv_obj_set_height( ui_Spinner5, 100);
lv_obj_set_x( ui_Spinner5, 175 );
lv_obj_set_y( ui_Spinner5, 90 );
lv_obj_set_align( ui_Spinner5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner5, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_color(ui_Spinner5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Spinner5, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner5, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Label32 = lv_label_create(ui_Display);
lv_obj_set_width( ui_Label32, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label32, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label32, -104 );
lv_obj_set_y( ui_Label32, -133 );
lv_obj_set_align( ui_Label32, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label32,"Display");

lv_obj_add_event_cb(ui_back_to_index1, ui_event_back_to_index1, LV_EVENT_ALL, NULL);

}
