// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: FullTest

#include "../ui.h"

void ui_IO_screen_init(void)
{
ui_IO = lv_obj_create(NULL);
lv_obj_clear_flag( ui_IO, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_back_to_index7 = lv_btn_create(ui_IO);
lv_obj_set_width( ui_back_to_index7, 100);
lv_obj_set_height( ui_back_to_index7, 50);
lv_obj_add_flag( ui_back_to_index7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_back_to_index7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_back_to_index7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label23 = lv_label_create(ui_back_to_index7);
lv_obj_set_width( ui_Label23, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label23, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label23, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label23,"BACK");
lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel8 = lv_obj_create(ui_IO);
lv_obj_set_width( ui_Panel8, 439);
lv_obj_set_height( ui_Panel8, 257);
lv_obj_set_x( ui_Panel8, 12 );
lv_obj_set_y( ui_Panel8, 55 );
lv_obj_set_flex_flow(ui_Panel8,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Panel8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel9 = lv_obj_create(ui_Panel8);
lv_obj_set_width( ui_Panel9, lv_pct(50));
lv_obj_set_height( ui_Panel9, lv_pct(100));
lv_obj_set_align( ui_Panel9, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel9,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Panel9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_io1_switch_box = lv_checkbox_create(ui_Panel9);
lv_checkbox_set_text(ui_io1_switch_box,"IO1");
lv_obj_set_width( ui_io1_switch_box, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_io1_switch_box, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_io1_switch_box, 6 );
lv_obj_set_y( ui_io1_switch_box, 32 );
lv_obj_add_flag( ui_io1_switch_box, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_io2_switch_box = lv_checkbox_create(ui_Panel9);
lv_checkbox_set_text(ui_io2_switch_box,"IO2");
lv_obj_set_width( ui_io2_switch_box, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_io2_switch_box, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_io2_switch_box, 6 );
lv_obj_set_y( ui_io2_switch_box, 32 );
lv_obj_add_flag( ui_io2_switch_box, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_io42_switch_box = lv_checkbox_create(ui_Panel9);
lv_checkbox_set_text(ui_io42_switch_box,"IO42");
lv_obj_set_width( ui_io42_switch_box, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_io42_switch_box, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_io42_switch_box, 6 );
lv_obj_set_y( ui_io42_switch_box, 32 );
lv_obj_add_flag( ui_io42_switch_box, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_io41_switch_box = lv_checkbox_create(ui_Panel9);
lv_checkbox_set_text(ui_io41_switch_box,"IO41");
lv_obj_set_width( ui_io41_switch_box, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_io41_switch_box, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_io41_switch_box, 6 );
lv_obj_set_y( ui_io41_switch_box, 32 );
lv_obj_add_flag( ui_io41_switch_box, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_io40_switch_box = lv_checkbox_create(ui_Panel9);
lv_checkbox_set_text(ui_io40_switch_box,"IO40");
lv_obj_set_width( ui_io40_switch_box, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_io40_switch_box, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_io40_switch_box, 6 );
lv_obj_set_y( ui_io40_switch_box, 32 );
lv_obj_add_flag( ui_io40_switch_box, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_io39_switch_box = lv_checkbox_create(ui_Panel9);
lv_checkbox_set_text(ui_io39_switch_box,"IO39");
lv_obj_set_width( ui_io39_switch_box, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_io39_switch_box, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_io39_switch_box, 6 );
lv_obj_set_y( ui_io39_switch_box, 32 );
lv_obj_add_flag( ui_io39_switch_box, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Panel10 = lv_obj_create(ui_Panel8);
lv_obj_set_width( ui_Panel10, lv_pct(50));
lv_obj_set_height( ui_Panel10, lv_pct(100));
lv_obj_set_align( ui_Panel10, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel10,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Panel10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_io7_switch_box = lv_checkbox_create(ui_Panel10);
lv_checkbox_set_text(ui_io7_switch_box,"IO7");
lv_obj_set_width( ui_io7_switch_box, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_io7_switch_box, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_io7_switch_box, 6 );
lv_obj_set_y( ui_io7_switch_box, 32 );
lv_obj_add_flag( ui_io7_switch_box, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_io6_switch_box = lv_checkbox_create(ui_Panel10);
lv_checkbox_set_text(ui_io6_switch_box,"IO6");
lv_obj_set_width( ui_io6_switch_box, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_io6_switch_box, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_io6_switch_box, 6 );
lv_obj_set_y( ui_io6_switch_box, 32 );
lv_obj_add_flag( ui_io6_switch_box, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_io46_switch_box = lv_checkbox_create(ui_Panel10);
lv_checkbox_set_text(ui_io46_switch_box,"IO46");
lv_obj_set_width( ui_io46_switch_box, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_io46_switch_box, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_io46_switch_box, 6 );
lv_obj_set_y( ui_io46_switch_box, 32 );
lv_obj_add_flag( ui_io46_switch_box, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Switch3 = lv_switch_create(ui_IO);
lv_obj_set_width( ui_Switch3, 63);
lv_obj_set_height( ui_Switch3, 33);
lv_obj_set_x( ui_Switch3, 175 );
lv_obj_set_y( ui_Switch3, -130 );
lv_obj_set_align( ui_Switch3, LV_ALIGN_CENTER );


ui_Label28 = lv_label_create(ui_IO);
lv_obj_set_width( ui_Label28, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label28, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label28, 75 );
lv_obj_set_y( ui_Label28, -131 );
lv_obj_set_align( ui_Label28, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label28,"Auto Play");
lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label38 = lv_label_create(ui_IO);
lv_obj_set_width( ui_Label38, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label38, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label38, -121 );
lv_obj_set_y( ui_Label38, -131 );
lv_obj_set_align( ui_Label38, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label38,"IO");

lv_obj_add_event_cb(ui_back_to_index7, ui_event_back_to_index7, LV_EVENT_ALL, NULL);

}
