// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: FullTest

#include "../ui.h"

void ui_I2C_screen_init(void)
{
ui_I2C = lv_obj_create(NULL);
lv_obj_clear_flag( ui_I2C, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_back_to_index3 = lv_btn_create(ui_I2C);
lv_obj_set_width( ui_back_to_index3, 100);
lv_obj_set_height( ui_back_to_index3, 50);
lv_obj_add_flag( ui_back_to_index3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_back_to_index3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_back_to_index3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label15 = lv_label_create(ui_back_to_index3);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"BACK");
lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel5 = lv_obj_create(ui_I2C);
lv_obj_set_width( ui_Panel5, 439);
lv_obj_set_height( ui_Panel5, 239);
lv_obj_set_x( ui_Panel5, 19 );
lv_obj_set_y( ui_Panel5, 62 );

ui_i2c_scan_log = lv_label_create(ui_Panel5);
lv_obj_set_width( ui_i2c_scan_log, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_i2c_scan_log, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_i2c_scan_log,".....");

ui_Label34 = lv_label_create(ui_I2C);
lv_obj_set_width( ui_Label34, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label34, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label34, -117 );
lv_obj_set_y( ui_Label34, -133 );
lv_obj_set_align( ui_Label34, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label34,"I2C");

ui_scan_i2c_btn = lv_btn_create(ui_I2C);
lv_obj_set_width( ui_scan_i2c_btn, 100);
lv_obj_set_height( ui_scan_i2c_btn, 50);
lv_obj_set_x( ui_scan_i2c_btn, 166 );
lv_obj_set_y( ui_scan_i2c_btn, -130 );
lv_obj_set_align( ui_scan_i2c_btn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_scan_i2c_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_scan_i2c_btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label22 = lv_label_create(ui_scan_i2c_btn);
lv_obj_set_width( ui_Label22, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label22, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label22, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label22,"Scan");
lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_back_to_index3, ui_event_back_to_index3, LV_EVENT_ALL, NULL);

}
