// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: FullTest

#include "../ui.h"

void ui_Index_screen_init(void)
{
ui_Index = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Index, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_Index,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Index, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

ui_Panel1 = lv_obj_create(ui_Index);
lv_obj_set_width( ui_Panel1, lv_pct(100));
lv_obj_set_height( ui_Panel1, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_go_to_touch_page = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_go_to_touch_page, 130);
lv_obj_set_height( ui_go_to_touch_page, 60);
lv_obj_set_align( ui_go_to_touch_page, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_go_to_touch_page, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_go_to_touch_page, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_go_to_touch_page);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Touch");
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_go_to_screen_page = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_go_to_screen_page, 130);
lv_obj_set_height( ui_go_to_screen_page, 60);
lv_obj_set_align( ui_go_to_screen_page, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_go_to_screen_page, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_go_to_screen_page, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_go_to_screen_page, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_go_to_screen_page, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_go_to_screen_page);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Display");
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_go_to_sound_page = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_go_to_sound_page, 130);
lv_obj_set_height( ui_go_to_sound_page, 60);
lv_obj_set_align( ui_go_to_sound_page, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_go_to_sound_page, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_go_to_sound_page, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_go_to_sound_page, lv_color_hex(0x3BFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_go_to_sound_page, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_go_to_sound_page);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Sound");
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_Index);
lv_obj_set_width( ui_Panel2, lv_pct(100));
lv_obj_set_height( ui_Panel2, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_go_to_i2c_page = lv_btn_create(ui_Panel2);
lv_obj_set_width( ui_go_to_i2c_page, 130);
lv_obj_set_height( ui_go_to_i2c_page, 60);
lv_obj_set_align( ui_go_to_i2c_page, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_go_to_i2c_page, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_go_to_i2c_page, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_go_to_i2c_page, lv_color_hex(0xFF00E8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_go_to_i2c_page, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_go_to_i2c_page);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"I2C");
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_go_to_microsd_card_page = lv_btn_create(ui_Panel2);
lv_obj_set_width( ui_go_to_microsd_card_page, 130);
lv_obj_set_height( ui_go_to_microsd_card_page, 60);
lv_obj_set_align( ui_go_to_microsd_card_page, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_go_to_microsd_card_page, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_go_to_microsd_card_page, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_go_to_microsd_card_page, lv_color_hex(0x00E8FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_go_to_microsd_card_page, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_go_to_microsd_card_page);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"MicroSD");
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_go_to_otg_page = lv_btn_create(ui_Panel2);
lv_obj_set_width( ui_go_to_otg_page, 130);
lv_obj_set_height( ui_go_to_otg_page, 60);
lv_obj_set_align( ui_go_to_otg_page, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_go_to_otg_page, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_go_to_otg_page, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_go_to_otg_page, lv_color_hex(0x00FF96), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_go_to_otg_page, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_go_to_otg_page);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"OTG");
lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_Index);
lv_obj_set_width( ui_Panel3, lv_pct(100));
lv_obj_set_height( ui_Panel3, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_go_to_led_y_page = lv_btn_create(ui_Panel3);
lv_obj_set_width( ui_go_to_led_y_page, 130);
lv_obj_set_height( ui_go_to_led_y_page, 60);
lv_obj_set_align( ui_go_to_led_y_page, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_go_to_led_y_page, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_go_to_led_y_page, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_go_to_led_y_page, lv_color_hex(0xFFFC00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_go_to_led_y_page, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_go_to_led_y_page);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"LED-SW");
lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_go_to_btn_a_page = lv_btn_create(ui_Panel3);
lv_obj_set_width( ui_go_to_btn_a_page, 130);
lv_obj_set_height( ui_go_to_btn_a_page, 60);
lv_obj_set_align( ui_go_to_btn_a_page, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_go_to_btn_a_page, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_go_to_btn_a_page, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_go_to_btn_a_page, lv_color_hex(0xFF8C00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_go_to_btn_a_page, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_go_to_btn_a_page);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"IO");
lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_go_to_wifi_a_page = lv_btn_create(ui_Panel3);
lv_obj_set_width( ui_go_to_wifi_a_page, 130);
lv_obj_set_height( ui_go_to_wifi_a_page, 60);
lv_obj_set_align( ui_go_to_wifi_a_page, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_go_to_wifi_a_page, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_go_to_wifi_a_page, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_go_to_wifi_a_page, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_go_to_wifi_a_page, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label12 = lv_label_create(ui_go_to_wifi_a_page);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"WiFi");
lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_go_to_touch_page, ui_event_go_to_touch_page, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_go_to_screen_page, ui_event_go_to_screen_page, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_go_to_sound_page, ui_event_go_to_sound_page, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_go_to_i2c_page, ui_event_go_to_i2c_page, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_go_to_microsd_card_page, ui_event_go_to_microsd_card_page, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_go_to_otg_page, ui_event_go_to_otg_page, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_go_to_led_y_page, ui_event_go_to_led_y_page, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_go_to_btn_a_page, ui_event_go_to_btn_a_page, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_go_to_wifi_a_page, ui_event_go_to_wifi_a_page, LV_EVENT_ALL, NULL);

}
