// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: FullTest

#include "../ui.h"

void ui_LED_SW_screen_init(void)
{
ui_LED_SW = lv_obj_create(NULL);
lv_obj_clear_flag( ui_LED_SW, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_back_to_index6 = lv_btn_create(ui_LED_SW);
lv_obj_set_width( ui_back_to_index6, 100);
lv_obj_set_height( ui_back_to_index6, 50);
lv_obj_add_flag( ui_back_to_index6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_back_to_index6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_back_to_index6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label21 = lv_label_create(ui_back_to_index6);
lv_obj_set_width( ui_Label21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label21, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label21, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label21,"BACK");
lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_led_btn = lv_obj_create(ui_LED_SW);
lv_obj_set_width( ui_led_btn, 180);
lv_obj_set_height( ui_led_btn, 180);
lv_obj_set_x( ui_led_btn, -110 );
lv_obj_set_y( ui_led_btn, 18 );
lv_obj_set_align( ui_led_btn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_led_btn, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_led_btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_led_btn, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_led_btn, lv_color_hex(0xEFEFEF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_led_btn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_led_btn, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_led_btn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_led_btn, lv_color_hex(0xFFF700), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_led_btn, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_color(ui_led_btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(ui_led_btn, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Label24 = lv_label_create(ui_led_btn);
lv_obj_set_width( ui_Label24, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label24, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label24, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label24,"Press here");
lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label26 = lv_label_create(ui_LED_SW);
lv_obj_set_width( ui_Label26, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label26, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label26, 102 );
lv_obj_set_y( ui_Label26, 64 );
lv_label_set_text(ui_Label26,"LED Y");

ui_switch_y_status = lv_switch_create(ui_LED_SW);
lv_obj_set_width( ui_switch_y_status, 198);
lv_obj_set_height( ui_switch_y_status, 102);
lv_obj_set_x( ui_switch_y_status, 117 );
lv_obj_set_y( ui_switch_y_status, 23 );
lv_obj_set_align( ui_switch_y_status, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_switch_y_status, LV_OBJ_FLAG_CLICKABLE );    /// Flags


ui_Label27 = lv_label_create(ui_LED_SW);
lv_obj_set_width( ui_Label27, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label27, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label27, 334 );
lv_obj_set_y( ui_Label27, 101 );
lv_label_set_text(ui_Label27,"BTN A");

ui_Label37 = lv_label_create(ui_LED_SW);
lv_obj_set_width( ui_Label37, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label37, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label37, -99 );
lv_obj_set_y( ui_Label37, -132 );
lv_obj_set_align( ui_Label37, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label37,"LED-SW");

lv_obj_add_event_cb(ui_back_to_index6, ui_event_back_to_index6, LV_EVENT_ALL, NULL);

}
