// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: FullTest

#include "../ui.h"

void ui_MicroSD_Card_screen_init(void)
{
ui_MicroSD_Card = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MicroSD_Card, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_back_to_index4 = lv_btn_create(ui_MicroSD_Card);
lv_obj_set_width( ui_back_to_index4, 100);
lv_obj_set_height( ui_back_to_index4, 50);
lv_obj_add_flag( ui_back_to_index4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_back_to_index4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_back_to_index4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label17 = lv_label_create(ui_back_to_index4);
lv_obj_set_width( ui_Label17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label17, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label17,"BACK");
lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel6 = lv_obj_create(ui_MicroSD_Card);
lv_obj_set_width( ui_Panel6, 438);
lv_obj_set_height( ui_Panel6, 231);
lv_obj_set_x( ui_Panel6, 24 );
lv_obj_set_y( ui_Panel6, 68 );

ui_micro_sd_card_log = lv_label_create(ui_Panel6);
lv_obj_set_width( ui_micro_sd_card_log, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_micro_sd_card_log, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_micro_sd_card_log,"wait insert...");

ui_Label20 = lv_label_create(ui_MicroSD_Card);
lv_obj_set_width( ui_Label20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label20, 84 );
lv_obj_set_y( ui_Label20, -126 );
lv_obj_set_align( ui_Label20, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label20,"Detect:");
lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_microsd_card_detect_sw = lv_switch_create(ui_MicroSD_Card);
lv_obj_set_width( ui_microsd_card_detect_sw, 70);
lv_obj_set_height( ui_microsd_card_detect_sw, 40);
lv_obj_set_x( ui_microsd_card_detect_sw, 181 );
lv_obj_set_y( ui_microsd_card_detect_sw, -124 );
lv_obj_set_align( ui_microsd_card_detect_sw, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_microsd_card_detect_sw, LV_OBJ_FLAG_CLICKABLE );    /// Flags


ui_Label35 = lv_label_create(ui_MicroSD_Card);
lv_obj_set_width( ui_Label35, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label35, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label35, -81 );
lv_obj_set_y( ui_Label35, -133 );
lv_obj_set_align( ui_Label35, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label35,"MicroSD Card");

lv_obj_add_event_cb(ui_back_to_index4, ui_event_back_to_index4, LV_EVENT_ALL, NULL);

}
