// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: FullTest

#include "../ui.h"

void ui_Sound_screen_init(void)
{
ui_Sound = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Sound, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_back_to_index2 = lv_btn_create(ui_Sound);
lv_obj_set_width( ui_back_to_index2, 100);
lv_obj_set_height( ui_back_to_index2, 50);
lv_obj_add_flag( ui_back_to_index2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_back_to_index2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_back_to_index2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label13 = lv_label_create(ui_back_to_index2);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"BACK");
lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_play_sound_btn = lv_btn_create(ui_Sound);
lv_obj_set_width( ui_play_sound_btn, 135);
lv_obj_set_height( ui_play_sound_btn, 89);
lv_obj_set_x( ui_play_sound_btn, -109 );
lv_obj_set_y( ui_play_sound_btn, 7 );
lv_obj_set_align( ui_play_sound_btn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_play_sound_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_play_sound_btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label14 = lv_label_create(ui_play_sound_btn);
lv_obj_set_width( ui_Label14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label14, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label14,"Play");
lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_stop_sound_btn = lv_btn_create(ui_Sound);
lv_obj_set_width( ui_stop_sound_btn, 135);
lv_obj_set_height( ui_stop_sound_btn, 89);
lv_obj_set_x( ui_stop_sound_btn, 102 );
lv_obj_set_y( ui_stop_sound_btn, 7 );
lv_obj_set_align( ui_stop_sound_btn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_stop_sound_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_stop_sound_btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label16 = lv_label_create(ui_stop_sound_btn);
lv_obj_set_width( ui_Label16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label16,"Stop");
lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label33 = lv_label_create(ui_Sound);
lv_obj_set_width( ui_Label33, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label33, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label33, -102 );
lv_obj_set_y( ui_Label33, -133 );
lv_obj_set_align( ui_Label33, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label33,"Sound");

lv_obj_add_event_cb(ui_back_to_index2, ui_event_back_to_index2, LV_EVENT_ALL, NULL);

}
