// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: FullTest

#include "../ui.h"

void ui_Touch_screen_init(void)
{
ui_Touch = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Touch, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_back_to_index = lv_btn_create(ui_Touch);
lv_obj_set_width( ui_back_to_index, 100);
lv_obj_set_height( ui_back_to_index, 50);
lv_obj_add_flag( ui_back_to_index, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_back_to_index, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_back_to_index, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_back_to_index);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"BACK");
lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_free_drag_object = lv_obj_create(ui_Touch);
lv_obj_set_width( ui_free_drag_object, 60);
lv_obj_set_height( ui_free_drag_object, 60);
lv_obj_set_x( ui_free_drag_object, 165 );
lv_obj_set_y( ui_free_drag_object, 93 );
lv_obj_clear_flag( ui_free_drag_object, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC );    /// Flags

ui_Label10 = lv_label_create(ui_free_drag_object);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"Drag\nMe");

ui_Label31 = lv_label_create(ui_Touch);
lv_obj_set_width( ui_Label31, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label31, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label31, -106 );
lv_obj_set_y( ui_Label31, -132 );
lv_obj_set_align( ui_Label31, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label31,"Touch");

lv_obj_add_event_cb(ui_back_to_index, ui_event_back_to_index, LV_EVENT_ALL, NULL);

}
