// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: FullTest

#include "../ui.h"

void ui_USB_OTG_screen_init(void)
{
ui_USB_OTG = lv_obj_create(NULL);
lv_obj_clear_flag( ui_USB_OTG, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_back_to_index5 = lv_btn_create(ui_USB_OTG);
lv_obj_set_width( ui_back_to_index5, 100);
lv_obj_set_height( ui_back_to_index5, 50);
lv_obj_add_flag( ui_back_to_index5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_back_to_index5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_back_to_index5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label19 = lv_label_create(ui_back_to_index5);
lv_obj_set_width( ui_Label19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label19, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label19,"BACK");
lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label36 = lv_label_create(ui_USB_OTG);
lv_obj_set_width( ui_Label36, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label36, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label36, -96 );
lv_obj_set_y( ui_Label36, -133 );
lv_obj_set_align( ui_Label36, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label36,"USB-OTG");

lv_obj_add_event_cb(ui_back_to_index5, ui_event_back_to_index5, LV_EVENT_ALL, NULL);

}
