// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: FullTest

#include "../ui.h"

void ui_WiFi_screen_init(void)
{
ui_WiFi = lv_obj_create(NULL);
lv_obj_clear_flag( ui_WiFi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_back_to_index8 = lv_btn_create(ui_WiFi);
lv_obj_set_width( ui_back_to_index8, 100);
lv_obj_set_height( ui_back_to_index8, 50);
lv_obj_add_flag( ui_back_to_index8, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_back_to_index8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_back_to_index8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label25 = lv_label_create(ui_back_to_index8);
lv_obj_set_width( ui_Label25, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label25, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label25, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label25,"BACK");
lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel11 = lv_obj_create(ui_WiFi);
lv_obj_set_width( ui_Panel11, 444);
lv_obj_set_height( ui_Panel11, 232);
lv_obj_set_x( ui_Panel11, 17 );
lv_obj_set_y( ui_Panel11, 65 );

ui_wifi_scan_log = lv_label_create(ui_Panel11);
lv_obj_set_width( ui_wifi_scan_log, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_scan_log, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_wifi_scan_log,"...");

ui_stat_scan_wifi_btn = lv_btn_create(ui_WiFi);
lv_obj_set_width( ui_stat_scan_wifi_btn, 123);
lv_obj_set_height( ui_stat_scan_wifi_btn, 50);
lv_obj_set_x( ui_stat_scan_wifi_btn, 159 );
lv_obj_set_y( ui_stat_scan_wifi_btn, -128 );
lv_obj_set_align( ui_stat_scan_wifi_btn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_stat_scan_wifi_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_stat_scan_wifi_btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label29 = lv_label_create(ui_stat_scan_wifi_btn);
lv_obj_set_width( ui_Label29, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label29, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label29, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label29,"Start Scan");

ui_Label39 = lv_label_create(ui_WiFi);
lv_obj_set_width( ui_Label39, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label39, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label39, -115 );
lv_obj_set_y( ui_Label39, -132 );
lv_obj_set_align( ui_Label39, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label39,"WiFi");

lv_obj_add_event_cb(ui_back_to_index8, ui_event_back_to_index8, LV_EVENT_ALL, NULL);

}
