// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: FullTest

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Index
void ui_Index_screen_init(void);
lv_obj_t *ui_Index;
lv_obj_t *ui_Panel1;
void ui_event_go_to_touch_page( lv_event_t * e);
lv_obj_t *ui_go_to_touch_page;
lv_obj_t *ui_Label1;
void ui_event_go_to_screen_page( lv_event_t * e);
lv_obj_t *ui_go_to_screen_page;
lv_obj_t *ui_Label2;
void ui_event_go_to_sound_page( lv_event_t * e);
lv_obj_t *ui_go_to_sound_page;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Panel2;
void ui_event_go_to_i2c_page( lv_event_t * e);
lv_obj_t *ui_go_to_i2c_page;
lv_obj_t *ui_Label4;
void ui_event_go_to_microsd_card_page( lv_event_t * e);
lv_obj_t *ui_go_to_microsd_card_page;
lv_obj_t *ui_Label5;
void ui_event_go_to_otg_page( lv_event_t * e);
lv_obj_t *ui_go_to_otg_page;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Panel3;
void ui_event_go_to_led_y_page( lv_event_t * e);
lv_obj_t *ui_go_to_led_y_page;
lv_obj_t *ui_Label7;
void ui_event_go_to_btn_a_page( lv_event_t * e);
lv_obj_t *ui_go_to_btn_a_page;
lv_obj_t *ui_Label8;
void ui_event_go_to_wifi_a_page( lv_event_t * e);
lv_obj_t *ui_go_to_wifi_a_page;
lv_obj_t *ui_Label12;


// SCREEN: ui_Touch
void ui_Touch_screen_init(void);
lv_obj_t *ui_Touch;
void ui_event_back_to_index( lv_event_t * e);
lv_obj_t *ui_back_to_index;
lv_obj_t *ui_Label9;
lv_obj_t *ui_free_drag_object;
lv_obj_t *ui_Label10;
lv_obj_t *ui_Label31;


// SCREEN: ui_Display
void ui_Display_screen_init(void);
lv_obj_t *ui_Display;
void ui_event_back_to_index1( lv_event_t * e);
lv_obj_t *ui_back_to_index1;
lv_obj_t *ui_Label11;
lv_obj_t *ui_Spinner1;
lv_obj_t *ui_Spinner2;
lv_obj_t *ui_Spinner3;
lv_obj_t *ui_Colorwheel2;
lv_obj_t *ui_Spinner4;
lv_obj_t *ui_Spinner5;
lv_obj_t *ui_Label32;


// SCREEN: ui_Sound
void ui_Sound_screen_init(void);
lv_obj_t *ui_Sound;
void ui_event_back_to_index2( lv_event_t * e);
lv_obj_t *ui_back_to_index2;
lv_obj_t *ui_Label13;
lv_obj_t *ui_play_sound_btn;
lv_obj_t *ui_Label14;
lv_obj_t *ui_stop_sound_btn;
lv_obj_t *ui_Label16;
lv_obj_t *ui_Label33;


// SCREEN: ui_I2C
void ui_I2C_screen_init(void);
lv_obj_t *ui_I2C;
void ui_event_back_to_index3( lv_event_t * e);
lv_obj_t *ui_back_to_index3;
lv_obj_t *ui_Label15;
lv_obj_t *ui_Panel5;
lv_obj_t *ui_i2c_scan_log;
lv_obj_t *ui_Label34;
lv_obj_t *ui_scan_i2c_btn;
lv_obj_t *ui_Label22;


// SCREEN: ui_MicroSD_Card
void ui_MicroSD_Card_screen_init(void);
lv_obj_t *ui_MicroSD_Card;
void ui_event_back_to_index4( lv_event_t * e);
lv_obj_t *ui_back_to_index4;
lv_obj_t *ui_Label17;
lv_obj_t *ui_Panel6;
lv_obj_t *ui_micro_sd_card_log;
lv_obj_t *ui_Label20;
lv_obj_t *ui_microsd_card_detect_sw;
lv_obj_t *ui_Label35;


// SCREEN: ui_USB_OTG
void ui_USB_OTG_screen_init(void);
lv_obj_t *ui_USB_OTG;
void ui_event_back_to_index5( lv_event_t * e);
lv_obj_t *ui_back_to_index5;
lv_obj_t *ui_Label19;
lv_obj_t *ui_Label36;


// SCREEN: ui_LED_SW
void ui_LED_SW_screen_init(void);
lv_obj_t *ui_LED_SW;
void ui_event_back_to_index6( lv_event_t * e);
lv_obj_t *ui_back_to_index6;
lv_obj_t *ui_Label21;
lv_obj_t *ui_led_btn;
lv_obj_t *ui_Label24;
lv_obj_t *ui_Label26;
lv_obj_t *ui_switch_y_status;
lv_obj_t *ui_Label27;
lv_obj_t *ui_Label37;


// SCREEN: ui_IO
void ui_IO_screen_init(void);
lv_obj_t *ui_IO;
void ui_event_back_to_index7( lv_event_t * e);
lv_obj_t *ui_back_to_index7;
lv_obj_t *ui_Label23;
lv_obj_t *ui_Panel8;
lv_obj_t *ui_Panel9;
lv_obj_t *ui_io1_switch_box;
lv_obj_t *ui_io2_switch_box;
lv_obj_t *ui_io42_switch_box;
lv_obj_t *ui_io41_switch_box;
lv_obj_t *ui_io40_switch_box;
lv_obj_t *ui_io39_switch_box;
lv_obj_t *ui_Panel10;
lv_obj_t *ui_io7_switch_box;
lv_obj_t *ui_io6_switch_box;
lv_obj_t *ui_io46_switch_box;
lv_obj_t *ui_Switch3;
lv_obj_t *ui_Label28;
lv_obj_t *ui_Label38;


// SCREEN: ui_WiFi
void ui_WiFi_screen_init(void);
lv_obj_t *ui_WiFi;
void ui_event_back_to_index8( lv_event_t * e);
lv_obj_t *ui_back_to_index8;
lv_obj_t *ui_Label25;
lv_obj_t *ui_Panel11;
lv_obj_t *ui_wifi_scan_log;
lv_obj_t *ui_stat_scan_wifi_btn;
lv_obj_t *ui_Label29;
lv_obj_t *ui_Label39;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_go_to_touch_page( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Touch, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Touch_screen_init);
}
}
void ui_event_go_to_screen_page( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Display, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Display_screen_init);
}
}
void ui_event_go_to_sound_page( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Sound, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Sound_screen_init);
}
}
void ui_event_go_to_i2c_page( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_I2C, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_I2C_screen_init);
}
}
void ui_event_go_to_microsd_card_page( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_MicroSD_Card, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_MicroSD_Card_screen_init);
}
}
void ui_event_go_to_otg_page( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_USB_OTG, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_USB_OTG_screen_init);
}
}
void ui_event_go_to_led_y_page( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_LED_SW, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_LED_SW_screen_init);
}
}
void ui_event_go_to_btn_a_page( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_IO, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_IO_screen_init);
}
}
void ui_event_go_to_wifi_a_page( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_WiFi, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_WiFi_screen_init);
}
}
void ui_event_back_to_index( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Index, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Index_screen_init);
}
}
void ui_event_back_to_index1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Index, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Index_screen_init);
}
}
void ui_event_back_to_index2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Index, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Index_screen_init);
}
}
void ui_event_back_to_index3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Index, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Index_screen_init);
}
}
void ui_event_back_to_index4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Index, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Index_screen_init);
}
}
void ui_event_back_to_index5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Index, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Index_screen_init);
}
}
void ui_event_back_to_index6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Index, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Index_screen_init);
}
}
void ui_event_back_to_index7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Index, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Index_screen_init);
}
}
void ui_event_back_to_index8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Index, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Index_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Index_screen_init();
ui_Touch_screen_init();
ui_Display_screen_init();
ui_Sound_screen_init();
ui_I2C_screen_init();
ui_MicroSD_Card_screen_init();
ui_USB_OTG_screen_init();
ui_LED_SW_screen_init();
ui_IO_screen_init();
ui_WiFi_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Index);
}
