// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: FullTest

#ifndef _FULLTEST_UI_H
#define _FULLTEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Index
void ui_Index_screen_init(void);
extern lv_obj_t *ui_Index;
extern lv_obj_t *ui_Panel1;
void ui_event_go_to_touch_page( lv_event_t * e);
extern lv_obj_t *ui_go_to_touch_page;
extern lv_obj_t *ui_Label1;
void ui_event_go_to_screen_page( lv_event_t * e);
extern lv_obj_t *ui_go_to_screen_page;
extern lv_obj_t *ui_Label2;
void ui_event_go_to_sound_page( lv_event_t * e);
extern lv_obj_t *ui_go_to_sound_page;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Panel2;
void ui_event_go_to_i2c_page( lv_event_t * e);
extern lv_obj_t *ui_go_to_i2c_page;
extern lv_obj_t *ui_Label4;
void ui_event_go_to_microsd_card_page( lv_event_t * e);
extern lv_obj_t *ui_go_to_microsd_card_page;
extern lv_obj_t *ui_Label5;
void ui_event_go_to_otg_page( lv_event_t * e);
extern lv_obj_t *ui_go_to_otg_page;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Panel3;
void ui_event_go_to_led_y_page( lv_event_t * e);
extern lv_obj_t *ui_go_to_led_y_page;
extern lv_obj_t *ui_Label7;
void ui_event_go_to_btn_a_page( lv_event_t * e);
extern lv_obj_t *ui_go_to_btn_a_page;
extern lv_obj_t *ui_Label8;
void ui_event_go_to_wifi_a_page( lv_event_t * e);
extern lv_obj_t *ui_go_to_wifi_a_page;
extern lv_obj_t *ui_Label12;
// SCREEN: ui_Touch
void ui_Touch_screen_init(void);
extern lv_obj_t *ui_Touch;
void ui_event_back_to_index( lv_event_t * e);
extern lv_obj_t *ui_back_to_index;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_free_drag_object;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Label31;
// SCREEN: ui_Display
void ui_Display_screen_init(void);
extern lv_obj_t *ui_Display;
void ui_event_back_to_index1( lv_event_t * e);
extern lv_obj_t *ui_back_to_index1;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Spinner1;
extern lv_obj_t *ui_Spinner2;
extern lv_obj_t *ui_Spinner3;
extern lv_obj_t *ui_Colorwheel2;
extern lv_obj_t *ui_Spinner4;
extern lv_obj_t *ui_Spinner5;
extern lv_obj_t *ui_Label32;
// SCREEN: ui_Sound
void ui_Sound_screen_init(void);
extern lv_obj_t *ui_Sound;
void ui_event_back_to_index2( lv_event_t * e);
extern lv_obj_t *ui_back_to_index2;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_play_sound_btn;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_stop_sound_btn;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_Label33;
// SCREEN: ui_I2C
void ui_I2C_screen_init(void);
extern lv_obj_t *ui_I2C;
void ui_event_back_to_index3( lv_event_t * e);
extern lv_obj_t *ui_back_to_index3;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_i2c_scan_log;
extern lv_obj_t *ui_Label34;
extern lv_obj_t *ui_scan_i2c_btn;
extern lv_obj_t *ui_Label22;
// SCREEN: ui_MicroSD_Card
void ui_MicroSD_Card_screen_init(void);
extern lv_obj_t *ui_MicroSD_Card;
void ui_event_back_to_index4( lv_event_t * e);
extern lv_obj_t *ui_back_to_index4;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_micro_sd_card_log;
extern lv_obj_t *ui_Label20;
extern lv_obj_t *ui_microsd_card_detect_sw;
extern lv_obj_t *ui_Label35;
// SCREEN: ui_USB_OTG
void ui_USB_OTG_screen_init(void);
extern lv_obj_t *ui_USB_OTG;
void ui_event_back_to_index5( lv_event_t * e);
extern lv_obj_t *ui_back_to_index5;
extern lv_obj_t *ui_Label19;
extern lv_obj_t *ui_Label36;
// SCREEN: ui_LED_SW
void ui_LED_SW_screen_init(void);
extern lv_obj_t *ui_LED_SW;
void ui_event_back_to_index6( lv_event_t * e);
extern lv_obj_t *ui_back_to_index6;
extern lv_obj_t *ui_Label21;
extern lv_obj_t *ui_led_btn;
extern lv_obj_t *ui_Label24;
extern lv_obj_t *ui_Label26;
extern lv_obj_t *ui_switch_y_status;
extern lv_obj_t *ui_Label27;
extern lv_obj_t *ui_Label37;
// SCREEN: ui_IO
void ui_IO_screen_init(void);
extern lv_obj_t *ui_IO;
void ui_event_back_to_index7( lv_event_t * e);
extern lv_obj_t *ui_back_to_index7;
extern lv_obj_t *ui_Label23;
extern lv_obj_t *ui_Panel8;
extern lv_obj_t *ui_Panel9;
extern lv_obj_t *ui_io1_switch_box;
extern lv_obj_t *ui_io2_switch_box;
extern lv_obj_t *ui_io42_switch_box;
extern lv_obj_t *ui_io41_switch_box;
extern lv_obj_t *ui_io40_switch_box;
extern lv_obj_t *ui_io39_switch_box;
extern lv_obj_t *ui_Panel10;
extern lv_obj_t *ui_io7_switch_box;
extern lv_obj_t *ui_io6_switch_box;
extern lv_obj_t *ui_io46_switch_box;
extern lv_obj_t *ui_Switch3;
extern lv_obj_t *ui_Label28;
extern lv_obj_t *ui_Label38;
// SCREEN: ui_WiFi
void ui_WiFi_screen_init(void);
extern lv_obj_t *ui_WiFi;
void ui_event_back_to_index8( lv_event_t * e);
extern lv_obj_t *ui_back_to_index8;
extern lv_obj_t *ui_Label25;
extern lv_obj_t *ui_Panel11;
extern lv_obj_t *ui_wifi_scan_log;
extern lv_obj_t *ui_stat_scan_wifi_btn;
extern lv_obj_t *ui_Label29;
extern lv_obj_t *ui_Label39;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
